/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Mission {
  'status' : MissionStatus,
  'title' : string,
  'xpReward' : bigint,
  'difficulty' : bigint,
  'objectives' : string,
  'location' : string,
}
export type MissionOutcome = { 'fail' : null } |
  { 'success' : null };
export type MissionStatus = { 'completed' : null } |
  { 'locked' : null } |
  { 'available' : null };
export interface Profile {
  'xp' : bigint,
  'username' : string,
  'level' : bigint,
  'stats' : Stats,
}
export interface SquadMember { 'role' : string, 'profile' : Profile }
export interface Stats {
  'speed' : bigint,
  'defense' : bigint,
  'attack' : bigint,
}
export interface _SERVICE {
  'addSquadMember' : ActorMethod<[string, string], undefined>,
  'completeMission' : ActorMethod<[bigint, MissionOutcome], undefined>,
  'getGlobalLocations' : ActorMethod<[], Array<string>>,
  'getMissions' : ActorMethod<[], Array<Mission>>,
  'getProfile' : ActorMethod<[], Profile>,
  'getSquad' : ActorMethod<[], Array<SquadMember>>,
  'hasCompletedMission' : ActorMethod<[bigint], boolean>,
  'register' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];