/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MissionOutcome = IDL.Variant({
  'fail' : IDL.Null,
  'success' : IDL.Null,
});
export const MissionStatus = IDL.Variant({
  'completed' : IDL.Null,
  'locked' : IDL.Null,
  'available' : IDL.Null,
});
export const Mission = IDL.Record({
  'status' : MissionStatus,
  'title' : IDL.Text,
  'xpReward' : IDL.Nat,
  'difficulty' : IDL.Nat,
  'objectives' : IDL.Text,
  'location' : IDL.Text,
});
export const Stats = IDL.Record({
  'speed' : IDL.Nat,
  'defense' : IDL.Nat,
  'attack' : IDL.Nat,
});
export const Profile = IDL.Record({
  'xp' : IDL.Nat,
  'username' : IDL.Text,
  'level' : IDL.Nat,
  'stats' : Stats,
});
export const SquadMember = IDL.Record({
  'role' : IDL.Text,
  'profile' : Profile,
});

export const idlService = IDL.Service({
  'addSquadMember' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'completeMission' : IDL.Func([IDL.Nat, MissionOutcome], [], []),
  'getGlobalLocations' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getMissions' : IDL.Func([], [IDL.Vec(Mission)], ['query']),
  'getProfile' : IDL.Func([], [Profile], ['query']),
  'getSquad' : IDL.Func([], [IDL.Vec(SquadMember)], ['query']),
  'hasCompletedMission' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'register' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MissionOutcome = IDL.Variant({
    'fail' : IDL.Null,
    'success' : IDL.Null,
  });
  const MissionStatus = IDL.Variant({
    'completed' : IDL.Null,
    'locked' : IDL.Null,
    'available' : IDL.Null,
  });
  const Mission = IDL.Record({
    'status' : MissionStatus,
    'title' : IDL.Text,
    'xpReward' : IDL.Nat,
    'difficulty' : IDL.Nat,
    'objectives' : IDL.Text,
    'location' : IDL.Text,
  });
  const Stats = IDL.Record({
    'speed' : IDL.Nat,
    'defense' : IDL.Nat,
    'attack' : IDL.Nat,
  });
  const Profile = IDL.Record({
    'xp' : IDL.Nat,
    'username' : IDL.Text,
    'level' : IDL.Nat,
    'stats' : Stats,
  });
  const SquadMember = IDL.Record({ 'role' : IDL.Text, 'profile' : Profile });
  
  return IDL.Service({
    'addSquadMember' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'completeMission' : IDL.Func([IDL.Nat, MissionOutcome], [], []),
    'getGlobalLocations' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getMissions' : IDL.Func([], [IDL.Vec(Mission)], ['query']),
    'getProfile' : IDL.Func([], [Profile], ['query']),
    'getSquad' : IDL.Func([], [IDL.Vec(SquadMember)], ['query']),
    'hasCompletedMission' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'register' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };