/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Stats {
    speed: bigint;
    defense: bigint;
    attack: bigint;
}
export interface SquadMember {
    role: string;
    profile: Profile;
}
export interface Profile {
    xp: bigint;
    username: string;
    level: bigint;
    stats: Stats;
}
export interface Mission {
    status: MissionStatus;
    title: string;
    xpReward: bigint;
    difficulty: bigint;
    objectives: string;
    location: string;
}
export enum MissionOutcome {
    fail = "fail",
    success = "success"
}
export enum MissionStatus {
    completed = "completed",
    locked = "locked",
    available = "available"
}
export interface backendInterface {
    addSquadMember(name: string, role: string): Promise<void>;
    completeMission(missionId: bigint, outcome: MissionOutcome): Promise<void>;
    getGlobalLocations(): Promise<Array<string>>;
    getMissions(): Promise<Array<Mission>>;
    getProfile(): Promise<Profile>;
    getSquad(): Promise<Array<SquadMember>>;
    hasCompletedMission(missionId: bigint): Promise<boolean>;
    register(username: string): Promise<void>;
}
import type { Mission as _Mission, MissionOutcome as _MissionOutcome, MissionStatus as _MissionStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addSquadMember(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSquadMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSquadMember(arg0, arg1);
            return result;
        }
    }
    async completeMission(arg0: bigint, arg1: MissionOutcome): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeMission(arg0, to_candid_MissionOutcome_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeMission(arg0, to_candid_MissionOutcome_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getGlobalLocations(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGlobalLocations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGlobalLocations();
            return result;
        }
    }
    async getMissions(): Promise<Array<Mission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMissions();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMissions();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(): Promise<Profile> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return result;
        }
    }
    async getSquad(): Promise<Array<SquadMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSquad();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSquad();
            return result;
        }
    }
    async hasCompletedMission(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasCompletedMission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasCompletedMission(arg0);
            return result;
        }
    }
    async register(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0);
            return result;
        }
    }
}
function from_candid_MissionStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MissionStatus): MissionStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Mission_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Mission): Mission {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _MissionStatus;
    title: string;
    xpReward: bigint;
    difficulty: bigint;
    objectives: string;
    location: string;
}): {
    status: MissionStatus;
    title: string;
    xpReward: bigint;
    difficulty: bigint;
    objectives: string;
    location: string;
} {
    return {
        status: from_candid_MissionStatus_n6(_uploadFile, _downloadFile, value.status),
        title: value.title,
        xpReward: value.xpReward,
        difficulty: value.difficulty,
        objectives: value.objectives,
        location: value.location
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: null;
} | {
    locked: null;
} | {
    available: null;
}): MissionStatus {
    return "completed" in value ? MissionStatus.completed : "locked" in value ? MissionStatus.locked : "available" in value ? MissionStatus.available : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Mission>): Array<Mission> {
    return value.map((x)=>from_candid_Mission_n4(_uploadFile, _downloadFile, x));
}
function to_candid_MissionOutcome_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MissionOutcome): _MissionOutcome {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MissionOutcome): {
    fail: null;
} | {
    success: null;
} {
    return value == MissionOutcome.fail ? {
        fail: null
    } : value == MissionOutcome.success ? {
        success: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
